### PR TITLE
Use AWS cli when available

### LINKED ISSUE #81: Support to use AWS IAM role
I am using kube2iam to attach iam roles to pods. Would be awesome if we can support the IAM role in the statefulset.

Currently if we ignore the aws credentials part, it will error up and stop with "Incorrect number of arguments for host add command.". Would be better if we can make the credentials part as a non required field.

### PR DESCRIPTION
**Pull request by endrec**
This PR
- updates Azure CLI
- adds AWS CLI to docker
- adds kmsKeyId and storageClass options to S3 plan
- changes `pkg/backup/s3.go` to use AWS cli for AWS S3 (if it's available in the docker image)

Fixes #81, as AWS cli natively uses IAM role, or any other available authentication mechanism (e.g. service role).

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @endrec

**Comment by endrec** [comment]
@stefanprodan Would it be possible to make this a release?

**Comment by stefanprodan** [comment]
Release is on Docker Hub: `stefanprodan/mgob:1.2`

**Comment by endrec** [comment]
Thanks!

**Pull request merged**
