### PR TITLE
uri need to be encapsuled by double quote

### PR DESCRIPTION
**Pull request by maulal**
Hi,
I found a bug with password composed by single quote and the usage of the target.uri in the config file. The usage of target.uri is mandatory when we used specials characters in the password, because we cannot protect both single quote and double quote in password with the mongo tools parameters :'(

As you know, username and password should be encode to  support special characters, but some characters stay unchanged even encoded, it's the case for single quote.
In situation where you put a single quote in the password, and the uri is not protected by double quote, the command will fail because of the single quote remaining unchanged and considered by the command as a separator not part of the password.

To test all of that, you can try with this password `AZE/\"'&@$*AZE`.

Without single or double quote:
~~~
mongodb@mon-backup-rs0-dev-0:~$ mongodump --host mon-rs0-dev -u backup -p AZE/\"'&@$*AZE
>
> ^C
~~~

With double quote:
~~~
mongodb@mon-backup-rs0-dev-0:~$ mongodump --host mon-rs0-dev -u backup -p "AZE/\"'&@$*AZE"
2020-05-14T12:37:49.845+0000    Failed: can't create session: could not connect to server: connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.
~~~

With single quote:
~~~
mongodb@mon-backup-rs0-dev-0:~$ mongodump --host mon-rs0-dev -u backup -p 'AZE/\"'&@$*AZE'
>
> ^C
~~~

That's why uri is mandatory for this case (`AZE/\"'&@$*AZE` become `AZE%2F%5C%22'%26%40%24*AZE` when encoded):

~~~
mongodb@mon-backup-rs0-dev-0:~$ mongodump --uri "mongodb://backup:AZE%2F%5C%22'%26%40%24*AZE@mon-rs0-dev:27017/?authSource=admin"
2020-05-14T12:43:40.110+0000    writing admin.system.users to
2020-05-14T12:43:40.111+0000    done dumping admin.system.users (5 documents)
2020-05-14T12:43:40.112+0000    writing admin.system.roles to
2020-05-14T12:43:40.113+0000    done dumping admin.system.roles (1 document)
2020-05-14T12:43:40.114+0000    writing admin.system.version to
2020-05-14T12:43:40.115+0000    done dumping admin.system.version (2 documents)
~~~

and without double quote it's still failling:

~~~
mongodb@mon-backup-rs0-dev-0:~$ mongodump --uri mongodb://backup:AZE%2F%5C%22'%26%40%24*AZE@mon-rs0-dev:27017/?authSource=admin
>
> ^C
~~~

Best regards,

Thanks a lot for your job :)

### CODE REVIEW

**Comment by stefanprodan** [comment]
Can you please bump the mongo-tools version to `4.2.1-r1` in here https://github.com/stefanprodan/mgob/blob/master/Dockerfile#L21 the r0 is gone.

**Comment by maulal** [comment]
Hi,
I've seen that we can escape the character... never seen that before :'(

~~~
mongodb@mon-backup-rs0-dev-0:~$ mongodump --host mon-rs0-dev -u backup -p "AZE/\\\"'&@\$*AZE"
2020-05-14T14:18:07.442+0000    writing admin.system.users to
2020-05-14T14:18:07.443+0000    done dumping admin.system.users (5 documents)
2020-05-14T14:18:07.444+0000    writing admin.system.roles to
2020-05-14T14:18:07.445+0000    done dumping admin.system.roles (1 document)
2020-05-14T14:18:07.445+0000    writing admin.system.version to
2020-05-14T14:18:07.446+0000    done dumping admin.system.version (2 documents)
~~~

But it needs to be encapsuled by double quote.

best regards,

**Comment by maulal** [comment]
Hi,
I think the trouble during the ci execution is linked to the azure-cli version requirement that cannot be fullfilled.

I can try to update it... but i'm not using azure... so i will not be able to test this change... Do you think it's acceptable ? or do you prefer keep this part on your own ?

Best regards,

**Comment by stefanprodan** [comment]
I don't use Azure either. If you can please try to update it, the Azure CLI version is super old anyway.

**Comment by maulal** [comment]
I also had to upgrade python2 to python3.

**Pull request merged**
